name: Tests
on:
  pull_request:
    branches: [main]
  release:
    types: [published]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: brew install bash
      - run: test/bats/bin/bats --tap test
